In [2]:
!pip install pycuber
import pycuber as pc
import random
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
# Create a Cube object
mycube = pc.Cube()
mixed_cube1 = pc.Cube()
mixed_cube2 = pc.Cube()
# Do something at the cube.


In [3]:
mycube = pc.Cube()
print(mycube)

         [y][y][y]
         [y][y][y]
         [y][y][y]
[r][r][r][g][g][g][o][o][o][b][b][b]
[r][r][r][g][g][g][o][o][o][b][b][b]
[r][r][r][g][g][g][o][o][o][b][b][b]
         [w][w][w]
         [w][w][w]
         [w][w][w]



In [4]:
print(mycube.get_face("U")[1][1])

[y]


In [5]:
mycube.select_type

<bound method Cube.select_type of             
            
            
                        
                        
                        
            
            
            
>

In [6]:
mycube

In [7]:

mycube = pc.Cube()

# Create a copy of mycube
cube = mycube.copy()


In [8]:
print(cube)
print(mycube)

         [y][y][y]
         [y][y][y]
         [y][y][y]
[r][r][r][g][g][g][o][o][o][b][b][b]
[r][r][r][g][g][g][o][o][o][b][b][b]
[r][r][r][g][g][g][o][o][o][b][b][b]
         [w][w][w]
         [w][w][w]
         [w][w][w]

         [y][y][y]
         [y][y][y]
         [y][y][y]
[r][r][r][g][g][g][o][o][o][b][b][b]
[r][r][r][g][g][g][o][o][o][b][b][b]
[r][r][r][g][g][g][o][o][o][b][b][b]
         [w][w][w]
         [w][w][w]
         [w][w][w]



In [9]:
mycube("U")

In [10]:
cube("U")

In [11]:
print(cube)
print(mycube)

         [y][y][y]
         [y][y][y]
         [y][y][y]
[g][g][g][o][o][o][b][b][b][r][r][r]
[r][r][r][g][g][g][o][o][o][b][b][b]
[r][r][r][g][g][g][o][o][o][b][b][b]
         [w][w][w]
         [w][w][w]
         [w][w][w]

         [y][y][y]
         [y][y][y]
         [y][y][y]
[g][g][g][o][o][o][b][b][b][r][r][r]
[r][r][r][g][g][g][o][o][o][b][b][b]
[r][r][r][g][g][g][o][o][o][b][b][b]
         [w][w][w]
         [w][w][w]
         [w][w][w]



In [12]:
move_dict = {
    1: "R",
    2: "R'",
    3: "R2",
    4: "L",
    5: "L'",
    6: "L2",
    7: "U",
    8: "U'",
    9: "U2",
    10: "D",
    11: "D'",
    12: "D2",
    13: "F",
    14: "F'",
    15: "F2",
    16: "B",
    17: "B'",
    18: "B2"
}


In [13]:
my_moves = [1, 3, 2]  # R U R'

# Convert the numeric moves to the Rubik's cube notation
converted_moves = " ".join(move_dict[move] for move in my_moves)

# Apply the moves to the cube
mycube(converted_moves)

print(mycube)


         [y][y][w]
         [y][y][w]
         [y][y][w]
[g][g][g][o][o][b][o][o][o][g][r][r]
[r][r][r][g][g][b][o][o][o][g][b][b]
[r][r][r][g][g][r][b][b][b][o][b][b]
         [w][w][y]
         [w][w][y]
         [w][w][y]



In [14]:
mycube.get_face("D")

[[  ,   ,   ],
 [  ,   ,   ],
 [  ,   ,   ]]

In [15]:
#my_formula = pc.Formula("R U R' U' R' F R2 U' R' U' R U R' F'")
#my_formula.reverse()
#print(my_formula)

In [16]:
movement_number=0
Crossover_number=0


In [17]:
def random_generator(movement_number,k):
  x1=random.sample(range(0,movement_number),k)

  return x1
#z= random_generator(10)
#print(z)

In [18]:
mixed_cube1 = mycube.copy()
mixed_cube2 = mycube.copy()

In [19]:
cube_mixer = random.choices(range(1, 19), movement_number=8)
converted_moves = " ".join(move_dict[move] for move in cube_mixer)

print(cube_mixer)
# Apply the moves to the cube
mixed_cube1(converted_moves)
mixed_cube2(converted_moves)

TypeError: choices() got an unexpected keyword argument 'movement_number'

In [ ]:
mixed_cube1

In [ ]:
mixed_cube2

In [20]:
def generate_arrays(movement_number):

    arrays = []
    for _ in range(72):
        array = np.random.randint(1, 19, size=(movement_number,))
        arrays.append(array)
    return arrays

# Fonksiyonu çağırarak 50 adet dizi oluşturabilirsiniz.
my_arrays = generate_arrays(2)

In [21]:
my_arrays

[array([18,  1]),
 array([18,  2]),
 array([8, 4]),
 array([17,  5]),
 array([14,  6]),
 array([11, 17]),
 array([15,  7]),
 array([ 5, 11]),
 array([11,  9]),
 array([16,  5]),
 array([15, 12]),
 array([ 7, 11]),
 array([1, 4]),
 array([ 4, 11]),
 array([5, 9]),
 array([ 1, 13]),
 array([8, 6]),
 array([13,  4]),
 array([18, 16]),
 array([11, 16]),
 array([18, 16]),
 array([13, 18]),
 array([ 2, 14]),
 array([9, 2]),
 array([16, 12]),
 array([ 2, 14]),
 array([10,  4]),
 array([ 8, 15]),
 array([16, 15]),
 array([12, 15]),
 array([14, 17]),
 array([9, 6]),
 array([ 5, 11]),
 array([12, 16]),
 array([7, 4]),
 array([7, 9]),
 array([11,  3]),
 array([ 9, 10]),
 array([ 5, 13]),
 array([10, 13]),
 array([16,  5]),
 array([5, 8]),
 array([12,  8]),
 array([16, 14]),
 array([ 2, 13]),
 array([15,  1]),
 array([13, 18]),
 array([17, 16]),
 array([16,  7]),
 array([17,  8]),
 array([16, 11]),
 array([11,  6]),
 array([ 1, 11]),
 array([ 9, 16]),
 array([ 8, 10]),
 array([15,  8]),
 array([18

In [22]:
#my_arrays[15]=[6,2,16,2]

In [23]:
def score_cube(original_cube, mixed_cube):
    score = 0
    for face_name in ['U', 'D', 'L', 'R', 'F', 'B']:
        orig_face = original_cube.get_face(face_name)
        mixed_face = mixed_cube.get_face(face_name)
        for i in range(3):
            for j in range(3):
                if orig_face[i][j] == mixed_face[i][j]:
                    score = score + 1

    return score

# Get the score of the mixed cube
mycube = pc.Cube()
score = score_cube(mycube, mixed_cube1)
print("The score of the mixed cube is:", score)


The score of the mixed cube is: 32


In [24]:
converted_moves

"R R2 R'"

In [46]:
def fitness(movement_number ,Crossover_number):
  drw={}
  score=0
  mycube = pc.Cube()
  #global movement_number
  #global Crossover_number
  #global converted_moves
  mixed_cube_solution1= pc.Cube()
  mixed_cube_solution2= pc.Cube()

  my_arrays = generate_arrays(movement_number)

  cube_mixer = random.choices(range(1, 19), k=movement_number)
  converted_moves = " ".join(move_dict[move] for move in cube_mixer)

  def generate_unique_numbers():
      num1 = random.randint(0, 71)
      num2 = random.randint(0, 71)

      while num2 == num1:
          num2 = random.randint(0, 71)

      return num1, num2


  x1,x2 = generate_unique_numbers()



  def mutate(my_arrays, mutation_rate=0.05):
      # Choose a random individual from the population
      individual_index = random.randint(0, len(my_arrays) - 1)
      individual = my_arrays[individual_index]

      # Iterate through the genes of the chosen individual
      for i in range(len(individual)):
          # Check if a mutation occurs (based on the mutation rate)
          if random.random() < mutation_rate:
              # Choose a random move from the defined set
              move = random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])
              # Apply the move to the selected gene
              individual[i] = move

      # Replace the individual in the population with the mutated version
      my_arrays[individual_index] = individual

      return my_arrays
  i=0
  j=0
  while j<7200 and score<54:

    j=j+1

    if j>3000 and score>42:
      my_arrays = mutate(my_arrays,mutation_rate=0.15)
    elif j>5200 and score>42:
      my_arrays = mutate(my_arrays,mutation_rate=0.25)
    else:
      my_arrays = mutate(my_arrays)


    C1=my_arrays[x1]
    C2=my_arrays[x2]

    converted_moves1 = " ".join(move_dict[move] for move in C1)
    converted_moves2 = " ".join(move_dict[move] for move in C2)
    #print("CM1:",converted_moves1)
    #print("CM2:",converted_moves2)

    mixed_cube_solution1(converted_moves1)
    mixed_cube_solution2(converted_moves2)


    #print(C1)
    #print("MCS1:",mixed_cube_solution1)
    #print("MCS2:",mixed_cube_solution2)

    score1 = score_cube(mycube,mixed_cube_solution1)
    score2 = score_cube(mycube,mixed_cube_solution2)

    mixed_cube_solution1 = pc.Cube()
    mixed_cube_solution2 = pc.Cube()

    mixed_cube_solution1(converted_moves)
    mixed_cube_solution2(converted_moves)

    if j%400 == 0 :
      print("-------------------------------------------------------------")
      print("Steps",j)
      print("Best Score:",score)


    if score1 > score2:
      if score < score1:
        score = score1
      if Crossover_number>=1:
        t = random_generator(movement_number,Crossover_number)

        for z in t:
          my_arrays[x2][z]=my_arrays[x1][z]
      if score>=54:
            print("Solution is: ", converted_moves1 )
            print("Score is: ",score)
            drw[i]={"score":score}
            return drw,score


    else:
      if score < score2:
        score = score2
      if Crossover_number>=1:
        t = random_generator(movement_number , Crossover_number)
        for z in t:
          my_arrays[x1][z]=my_arrays[x2][z]

      if score>=54:
            print(" Solution is: ", converted_moves2 )
            print("Score is: ",score)
            drw[i]={"score":score}
            return drw,score



    x1,x2 = generate_unique_numbers()

    drw[i]={"score":score}
    i=i+1
  return drw,score

In [26]:

#print(my_arrays)

In [27]:
#cube_solver = fitness(my_arrays,8,2)

TypeError: fitness() takes 2 positional arguments but 3 were given

In [29]:
"""
print(my_arrays)
print("Apllied Moves:",cube_mixer)
print("Solution:",cube_mixer[::-1])
"""

'\nprint(my_arrays)\nprint("Apllied Moves:",cube_mixer)\nprint("Solution:",cube_mixer[::-1])\n'

In [ ]:
#mixed_cube1

In [ ]:
"""
df=pd.DataFrame(cube_solver)
df=df.transpose()
ax = df.plot(kind="line",title="Experimental Results")
ax.set_ylabel("Score")
ax.set_xlabel("Steps")

"""

In [62]:
import time
import matplotlib.pyplot as plt

def test_environment(movement_number, Crossover_number, mutation_rate, test_runs=25):
    run_times = []
    successful_solutions = 0
    
    for _ in range(test_runs):
        # Start the timer
        start_time = time.time()



        # Run the GA
        cube_solver, score= fitness(movement_number, Crossover_number)

        #print(type(cube_solver))
        # Stop the timer and record the run time
        end_time = time.time()
        run_time = end_time - start_time
        run_times.append(run_time)

        if score == 54:
            successful_solutions += 1


    # Calculate the average run time
    avg_run_time = sum(run_times) / len(run_times)
    avg_run_time_formatted = "{:.4f}".format(avg_run_time)
    # Plot the run times
    plt.plot(run_times)
    plt.xlabel('Test Run')
    plt.ylabel('Run Time (seconds)')
    plt.title(f'Test Run Times for {movement_number} move(s)\nCrossover: {Crossover_number} \n Successful Solution: {successful_solutions}')
    plt.text(0.01, 0.01, f'Average run time: {avg_run_time_formatted} seconds', transform=plt.gca().transAxes)
    plt.tight_layout()
        
    directory = r'C:\Users\mt660\Desktop\Alife_pics'
    
    filename = f"moves_{movement_number}_crossover_{Crossover_number}.png"
    plt.savefig(os.path.join(directory, filename))
    
    #plt.show()
  
  


In [63]:
#test_environment(2, 1, 0.2)


Solution is:  L' B'
Score is:  54
 Solution is:  B F2
Score is:  54
 Solution is:  R F2
Score is:  54
Solution is:  L2 U'
Score is:  54
 Solution is:  B D
Score is:  54
 Solution is:  F L'
Score is:  54
 Solution is:  D D'
Score is:  54
 Solution is:  R' B'
Score is:  54
 Solution is:  R' R
Score is:  54
-------------------------------------------------------------
Steps 400
Best Score: 42


KeyboardInterrupt: 

In [64]:
def runner():
    
    for i in range(0,13):
        for t in range(1,i):
            plt.clf()
            test_environment(i,t,0.1)
            #print("i= ",i," t= ",t)

    return print("test is over successfully")

In [ ]:
runner()

 Solution is:  D2 D2
Score is:  54
Solution is:  L' D2
Score is:  54
-------------------------------------------------------------
Steps 400
Best Score: 42
-------------------------------------------------------------
Steps 800
Best Score: 42
-------------------------------------------------------------
Steps 1200
Best Score: 42
-------------------------------------------------------------
Steps 1600
Best Score: 42
-------------------------------------------------------------
Steps 2000
Best Score: 42
-------------------------------------------------------------
Steps 2400
Best Score: 42
-------------------------------------------------------------
Steps 2800
Best Score: 42
-------------------------------------------------------------
Steps 3200
Best Score: 42
-------------------------------------------------------------
Steps 3600
Best Score: 42
-------------------------------------------------------------
Steps 4000
Best Score: 42
-----------------------------------------------------

-------------------------------------------------------------
Steps 4400
Best Score: 42
-------------------------------------------------------------
Steps 4800
Best Score: 42
-------------------------------------------------------------
Steps 5200
Best Score: 42
-------------------------------------------------------------
Steps 5600
Best Score: 42
-------------------------------------------------------------
Steps 6000
Best Score: 42
-------------------------------------------------------------
Steps 6400
Best Score: 42
-------------------------------------------------------------
Steps 6800
Best Score: 42
-------------------------------------------------------------
Steps 7200
Best Score: 42
-------------------------------------------------------------
Steps 400
Best Score: 36
-------------------------------------------------------------
Steps 800
Best Score: 42
 Solution is:  R F' D
Score is:  54
-------------------------------------------------------------
Steps 400
Best Score: 50

-------------------------------------------------------------
Steps 3200
Best Score: 39
-------------------------------------------------------------
Steps 3600
Best Score: 39
-------------------------------------------------------------
Steps 4000
Best Score: 39
-------------------------------------------------------------
Steps 4400
Best Score: 39
-------------------------------------------------------------
Steps 4800
Best Score: 39
-------------------------------------------------------------
Steps 5200
Best Score: 39
 Solution is:  U R2 D'
Score is:  54
 Solution is:  U' U2 U2
Score is:  54
 Solution is:  D B' B
Score is:  54
Solution is:  U' U2 D
Score is:  54
 Solution is:  D' D' U2
Score is:  54
Solution is:  R2 R2 F2
Score is:  54
-------------------------------------------------------------
Steps 400
Best Score: 42
-------------------------------------------------------------
Steps 800
Best Score: 42
-------------------------------------------------------------
Steps 1200
Bes

-------------------------------------------------------------
Steps 2000
Best Score: 42
-------------------------------------------------------------
Steps 2400
Best Score: 45
-------------------------------------------------------------
Steps 2800
Best Score: 45
 Solution is:  F' R D U'
Score is:  54
-------------------------------------------------------------
Steps 400
Best Score: 40
-------------------------------------------------------------
Steps 800
Best Score: 50
Solution is:  D2 F' F2 F
Score is:  54
Solution is:  R2 L D2 D'
Score is:  54
-------------------------------------------------------------
Steps 400
Best Score: 36
-------------------------------------------------------------
Steps 800
Best Score: 36
-------------------------------------------------------------
Steps 1200
Best Score: 41
-------------------------------------------------------------
Steps 1600
Best Score: 44
-------------------------------------------------------------
Steps 2000
Best Score: 44
-------

-------------------------------------------------------------
Steps 1600
Best Score: 48
-------------------------------------------------------------
Steps 2000
Best Score: 48
-------------------------------------------------------------
Steps 2400
Best Score: 48
-------------------------------------------------------------
Steps 2800
Best Score: 48
-------------------------------------------------------------
Steps 3200
Best Score: 48
-------------------------------------------------------------
Steps 3600
Best Score: 48
-------------------------------------------------------------
Steps 4000
Best Score: 48
-------------------------------------------------------------
Steps 4400
Best Score: 48
-------------------------------------------------------------
Steps 4800
Best Score: 48
-------------------------------------------------------------
Steps 5200
Best Score: 48
-------------------------------------------------------------
Steps 5600
Best Score: 48
--------------------------------

 Solution is:  B L' D' D
Score is:  54
-------------------------------------------------------------
Steps 400
Best Score: 40
-------------------------------------------------------------
Steps 800
Best Score: 42
-------------------------------------------------------------
Steps 1200
Best Score: 42
-------------------------------------------------------------
Steps 1600
Best Score: 42
-------------------------------------------------------------
Steps 2000
Best Score: 42
-------------------------------------------------------------
Steps 2400
Best Score: 42
-------------------------------------------------------------
Steps 2800
Best Score: 42
-------------------------------------------------------------
Steps 3200
Best Score: 42
-------------------------------------------------------------
Steps 3600
Best Score: 42
-------------------------------------------------------------
Steps 4000
Best Score: 42
-------------------------------------------------------------
Steps 4400
Best Score

-------------------------------------------------------------
Steps 4000
Best Score: 41
-------------------------------------------------------------
Steps 4400
Best Score: 41
-------------------------------------------------------------
Steps 4800
Best Score: 41
-------------------------------------------------------------
Steps 5200
Best Score: 41
-------------------------------------------------------------
Steps 5600
Best Score: 41
-------------------------------------------------------------
Steps 6000
Best Score: 41
-------------------------------------------------------------
Steps 6400
Best Score: 41
-------------------------------------------------------------
Steps 6800
Best Score: 41
-------------------------------------------------------------
Steps 7200
Best Score: 41
Solution is:  R' U2 U D2
Score is:  54
Solution is:  U' B L' F'
Score is:  54
 Solution is:  B' R R' B
Score is:  54
-------------------------------------------------------------
Steps 400
Best Score: 42
----

-------------------------------------------------------------
Steps 3200
Best Score: 42
-------------------------------------------------------------
Steps 3600
Best Score: 42
-------------------------------------------------------------
Steps 4000
Best Score: 42
-------------------------------------------------------------
Steps 4400
Best Score: 42
-------------------------------------------------------------
Steps 4800
Best Score: 42
-------------------------------------------------------------
Steps 5200
Best Score: 42
-------------------------------------------------------------
Steps 5600
Best Score: 42
-------------------------------------------------------------
Steps 6000
Best Score: 42
-------------------------------------------------------------
Steps 6400
Best Score: 42
-------------------------------------------------------------
Steps 6800
Best Score: 42
-------------------------------------------------------------
Steps 7200
Best Score: 42
--------------------------------

-------------------------------------------------------------
Steps 3200
Best Score: 39
-------------------------------------------------------------
Steps 3600
Best Score: 39
-------------------------------------------------------------
Steps 4000
Best Score: 39
-------------------------------------------------------------
Steps 4400
Best Score: 39
-------------------------------------------------------------
Steps 4800
Best Score: 39
-------------------------------------------------------------
Steps 5200
Best Score: 39
-------------------------------------------------------------
Steps 5600
Best Score: 39
-------------------------------------------------------------
Steps 6000
Best Score: 39
-------------------------------------------------------------
Steps 6400
Best Score: 39
-------------------------------------------------------------
Steps 6800
Best Score: 39
-------------------------------------------------------------
Steps 7200
Best Score: 39
--------------------------------

-------------------------------------------------------------
Steps 2400
Best Score: 42
-------------------------------------------------------------
Steps 2800
Best Score: 42
-------------------------------------------------------------
Steps 3200
Best Score: 42
-------------------------------------------------------------
Steps 3600
Best Score: 42
-------------------------------------------------------------
Steps 4000
Best Score: 42
-------------------------------------------------------------
Steps 4400
Best Score: 42
-------------------------------------------------------------
Steps 4800
Best Score: 42
-------------------------------------------------------------
Steps 5200
Best Score: 42
-------------------------------------------------------------
Steps 5600
Best Score: 42
-------------------------------------------------------------
Steps 6000
Best Score: 42
-------------------------------------------------------------
Steps 6400
Best Score: 42
Solution is:  R F' F' U' D'
Scor

-------------------------------------------------------------
Steps 7200
Best Score: 42
-------------------------------------------------------------
Steps 400
Best Score: 35
-------------------------------------------------------------
Steps 800
Best Score: 38
-------------------------------------------------------------
Steps 1200
Best Score: 42
-------------------------------------------------------------
Steps 1600
Best Score: 42
Solution is:  D' F' F B' F
Score is:  54
-------------------------------------------------------------
Steps 400
Best Score: 42
-------------------------------------------------------------
Steps 800
Best Score: 42
-------------------------------------------------------------
Steps 1200
Best Score: 42
 Solution is:  D R' D' D R'
Score is:  54
Solution is:  R2 L R2 U U'
Score is:  54
-------------------------------------------------------------
Steps 400
Best Score: 42
-------------------------------------------------------------
Steps 800
Best Score: 42
--

-------------------------------------------------------------
Steps 2000
Best Score: 34
-------------------------------------------------------------
Steps 2400
Best Score: 34
-------------------------------------------------------------
Steps 2800
Best Score: 42
-------------------------------------------------------------
Steps 3200
Best Score: 42
-------------------------------------------------------------
Steps 3600
Best Score: 42
-------------------------------------------------------------
Steps 4000
Best Score: 42
-------------------------------------------------------------
Steps 4400
Best Score: 42
-------------------------------------------------------------
Steps 4800
Best Score: 42
-------------------------------------------------------------
Steps 5200
Best Score: 42
-------------------------------------------------------------
Steps 5600
Best Score: 42
-------------------------------------------------------------
Steps 6000
Best Score: 42
--------------------------------

-------------------------------------------------------------
Steps 3600
Best Score: 35
-------------------------------------------------------------
Steps 4000
Best Score: 36
-------------------------------------------------------------
Steps 4400
Best Score: 36
-------------------------------------------------------------
Steps 4800
Best Score: 36
-------------------------------------------------------------
Steps 5200
Best Score: 36
-------------------------------------------------------------
Steps 5600
Best Score: 36
-------------------------------------------------------------
Steps 6000
Best Score: 36
-------------------------------------------------------------
Steps 6400
Best Score: 36
-------------------------------------------------------------
Steps 6800
Best Score: 36
-------------------------------------------------------------
Steps 7200
Best Score: 36
Solution is:  U' U U' L F'
Score is:  54
-------------------------------------------------------------
Steps 400
Best Sc

-------------------------------------------------------------
Steps 4000
Best Score: 40
-------------------------------------------------------------
Steps 4400
Best Score: 40
-------------------------------------------------------------
Steps 4800
Best Score: 40
-------------------------------------------------------------
Steps 5200
Best Score: 40
-------------------------------------------------------------
Steps 5600
Best Score: 40
-------------------------------------------------------------
Steps 6000
Best Score: 40
-------------------------------------------------------------
Steps 6400
Best Score: 40
-------------------------------------------------------------
Steps 6800
Best Score: 40
-------------------------------------------------------------
Steps 7200
Best Score: 40
Solution is:  D' U2 B2 B B
Score is:  54
-------------------------------------------------------------
Steps 400
Best Score: 32
-------------------------------------------------------------
Steps 800
Best Sco